### ISSUE TITLE
Add per server key to metrics

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/pushgo#200]
There are multiple statsd clients running on servers which are not differentiating their output. This is leading to records being lost due to collisions.

We may need to append a unique designator for each outbound statsd client (one per unique statsd instance per host) so that reported metrics do not collide.

**Comment by bbangert** [comment]
Our metrics are all completely inaccurate as a result of not post-fixing the machine name to the metric name. As such I'm dumping this in priority, 1.5 must include it so that we can have meaningful metrics.
