### ISSUE TITLE
Expose `TCP_USER_TIMEOUT` as a config option

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/pushgo#227]
This was added to the Linux kernel (2.6.37) in torvalds/linux@dca43c75e7e545694a9dd6288553f55c53e2a3a3. We'll want this to prune dead sockets to avoid long TCP retransmission delays. Go doesn't set this option for us, so we'll need to use `(golang.org/x/sys/unix).SetsockoptInt`.

**Comment by bbangert** [comment]
I've made PR's to our TCP settings that address this in the puppet repo.
