### ISSUE TITLE
Parallellize memcached operations

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/pushgo#58]
The following memcached operations could be run in parallel:

* `storeRegister()`: `storeAppIDArray` and `storeRec`.
* `FetchAll()`: Reading all channel records.
* `DropAll()`: Deleting the channels list and all channel records.

The maximum number of in-flight requests can be enforced via a `MaxParallel` option and a buffered channel to avoid spawning an excessive number of Goroutines.

**Comment by bbangert** [comment]
We're looking at dynamodb or a different persistent system, so this isn't required.
