### ISSUE TITLE
Consider a least-recently used map to reduce proxied requests

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/pushgo#76]
When a node receives a request for an unknown device, it broadcasts the request to a shuffled list of peers. As an optimization, we could keep an LRU map of device IDs to peers—when a proxied request succeeds, add an entry for this device. If the node receives a request for that device in the future, it can try proxying to that peer first, removing the mapping and falling back to broadcasting if the attempt fails.

On the other hand, a single node might not receive enough requests destined for a specific peer to make this worthwhile, and the requests are small as it is...

**Comment by bbangert** [comment]
Closed in favor of a more generic optimization issue, #213.
